recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, search, add_recipe

app_name = 'recipes'

urlpatterns = [
    path('', home),
    path('list/', RecipeListView.as_view(), name='list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('search/', search, name='search'),
    path('add_recipe/', add_recipe, name='add_recipe')
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Recipe(models.Model):
    name= models.CharField(max_length=50)
    ingredients= models.CharField(
        max_length=225,
        help_text="Enter the ingredients , separated by a comma."
    )
    cooking_time= models.IntegerField()
    difficulty= None
    pic= models.ImageField(upload_to='recipes', default='no_picture.jpg')

    @property
    def difficulty(self):
        ingredients = self.ingredients.split(", ")

        if self.cooking_time < 10 and len(ingredients) < 4:
            return "Easy"
        elif self.cooking_time < 10 and len(ingredients) >= 4:
            return "Medium"
        elif self.cooking_time >= 10 and len(ingredients) < 4:
            return "Intermediate"
        elif self.cooking_time >= 10 and len(ingredients) >= 4:
            return "Hard"
        return "Unknown"
    
    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse ('recipes:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username= models.CharField(max_length=50)
    password= models.TextField()
    email= models.TextField()
    pic= models.ImageField(upload_to='users', default='no_picture.jpg')

    def __str__(self):
        return str(self.username)

recipes/forms.py
from django import forms
from .models import Recipe

CHART__CHOICES = (
    ('#1', 'Bar chart'),
    ('#2', 'Pie chart'),
    ('#3', 'Line chart')
)

class RecipesSearchForm(forms.Form):
    recipe_ingredients = forms.CharField(max_length=120)
    chart_type = forms.ChoiceField(choices=CHART__CHOICES)

class AddRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "name",
            "ingredients",
            "cooking_time",
            "pic"
        ]

recipe_project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

def login_view(request):
    error_message = None
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('recipes:list')
        else:
            error_message = 'Oops, something went wrong!'

    context = {
        'form': form,
        'error_message': error_message
    }

    return render(request, 'auth/login.html', context)

def logout_view(request):
    logout(request)
    return render(request, 'auth/success.html')

recipes/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import RecipesSearchForm, AddRecipeForm
from .models import Recipe
from .utils import get_chart, get_recipename_from_id
import pandas as pd

# Create your views here.
def home(request):
    return render(request, 'recipes/recipes_home.html')

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/recipe-list.html'

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/recipe-detail.html'

@login_required
def search(request):
    form = RecipesSearchForm(request.POST or None)
    recipes_df = None
    chart = None

    if request.method == 'POST':
        recipe_ingredients = request.POST.get('recipe_ingredients')
        chart_type = request.POST.get('chart_type')

        qs = Recipe.objects.filter(ingredients__icontains=recipe_ingredients)

        if qs:
            recipes_df = pd.DataFrame(qs.values())
            
            recipes_df['id'] = recipes_df['id'].apply(get_recipename_from_id)

            chart = get_chart(chart_type, recipes_df, labels=recipes_df['cooking_time'].values)

            recipes_df = recipes_df.to_html()

    context = {
        "form": form,
        "recipes_df": recipes_df,
        "chart": chart
    }

    return render(request, 'recipes/search.html', context)

@login_required
def add_recipe(request):
    if request.method == 'POST':
        add_recipe_form = AddRecipeForm(request.POST, request.FILES)

        if add_recipe_form.is_valid():
            add_recipe_form.save()

            messages.success(request, "Recipe added successfully.")

            return redirect("recipes:list")
    else:
            add_recipe_form = AddRecipeForm()

    context = {
        "add_recipe_form": add_recipe_form
    }

    return render(request, "recipes/add_recipe.html", context)

users/views.py
from django.shortcuts import render

# Create your views here.

recipes/templates/recipes/add_recipe.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <style>
            .center {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            .container {
                background-color: #eee7dd;
            }
            .form-group {
                margin-bottom: 15px;
                margin-left: 5px;
            }
            .back-button {
                background-color: #a43f4c;
                color: #eee7dd;
            }
            .add-button {
                background-color: #5d6c56;
                color: #eee7dd;
            }
        </style>
    </head>
    <body class="container">
        <hr>
        <h1 style="text-align: center;">Add Recipe</h1>
        <hr>
        <br>

        {% if messages %}
            {% for message in messages %}
                <script>alert("{{ message }}");</script>
            {% endfor %}
        {% endif %}

        <div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_name">Recipe Name: </label>
                    <input type="text" name="name" id="id_name" required>
                </div>
                <div class="form-group">
                    <label for="id_ingredients">Ingredients: </label>
                    <textarea name="ingredients" id="id_ingredients" required></textarea>
                </div>
                <div class="form-group">
                    <label for="id_cooking_time">Cooking Time (in minutes): </label>
                    <input type="number" name="cooking_time" id="id_cooking_time" required>
                </div>
                <button type="submit" class="add-button form-group">Add Recipe</button>
            </form>
        </div>
        <br>
        <a href="{% url 'recipes:list' %}">
            <button type="button" class="center back-button">Back</button>
        </a>
    </body>
</html>

recipes/templates/recipes/recipe-detail.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <style>
            .center {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            .container {
                background-color: #eee7dd;
            }
            .back-button {
                background-color: #a43f4c;
                color: #eee7dd;
            }
        </style>
    </head>
    <title>
        Recipe Details
    </title>
    <body class="container">
        <hr>
        <h1 style="text-align: center;">Recipe Details: </h1>
        <hr>
        <br>
        <table border="1" cellpadding="5" cellspacing="5" style="margin: 0px auto;">
            <tr>
                <td>
                    <b>Title: </b> {{object.name}} <br>
                    <b>Ingredients: </b> {{object.ingredients}} <br>
                    <b>Cooking Time: </b> {{object.cooking_time}} <br>
                    <b>Difficulty: </b> {{object.difficulty}} <br>
                </td>
            </tr>
        </table>
        <br>
        <a href="{% url 'recipes:list' %}">
            <button type="button" class="center back-button">Back</button>
        </a>
    </body>
</html>

recipes/templates/recipes/recipe-list.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <style>
            .center {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            .container {
                background-color: #eee7dd;
            }
            .logout-button {
                background-color: #844734;
                color: #eee7dd;
            }
            .search-button {
                background-color: #9a404e;
                color: #eee7dd;
            }
            .about-button {
                background-color: #91867a;
                color: #eee7dd;
            }
            .add-button {
                background-color: #54614d;
                color: #eee7dd;
            }
            .details-button {
                background-color: #5d6c56;
                color: #eee7dd;
            }
            .navitem {
                display: block;
                text-align: center;
                text-decoration: none;
                flex: 1;
            }
        </style>
    </head>
    <body class="container">
        <nav>
            <a href="{% url 'logout' %}" class="navitem logout-button">Logout</a>
            <a href="{% url 'recipes:search' %}" class="navitem search-button">Search</a>
            <a href="{% url 'recipes:add_recipe' %}" class="navitem add-button">Add Recipe</a>
            <a href="https://sabwood.github.io/portfolio-website/" target="_blank" class="navitem about-button">About the Developer</a>
        </nav>
        <hr>
        <h1 style="text-align: center;">Recipes' List</h1>
        <hr>
        <br>
        <table border="1" cellpadding="5" cellspacing="5" style="margin: 0px auto;">
            <tr>
                <td>
                    <h3 style="text-align: center;">
                        Recipe Names: 
                    </h3>
                </td>
            </tr>
            {% for object in object_list %}
            <tr>
                <td>
                    <div style="text-align: center;">
                        {{object.name}}
                    </div>
                    <br>
                    <a href="{{object.get_absolute_url}}">
                        <button type="button" class="center details-button">
                            More Details: 
                        </button>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>

recipes/templates/recipes/recipes_home.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <style>
            .center {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            .container {
                background-color: #eee7dd;
            }
            .button {
                background-color: #844734;
                color: #eee7dd;
            }
        </style>
    </head>
    <title>
        Recipe App
    </title>
    <body class="container">
        <br>
        <br>
        <h1 style="text-align: center;">Start Cooking!</h1>
        <img src="{% static 'recipes/images/app-home.jpg' %}" alt="home" width="600" height="400" class="center">
        <a href="{% url 'login' %}">
            <button type="button" class="center button"> - Login Here - </button>
        </a>
    </body>
</html>

recipes/templates/recipes/search.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <style>
            .center {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
            .container {
                background-color: #eee7dd;
            }
            .back-button {
                background-color: #a43f4c;
                color: #eee7dd;
            }
            .search-button {
                background-color: #b74451;
                color: #eee7dd;
            }
        </style>
    </head>
    <body class="container">
        <hr>
        <h1 style="text-align: center;">Search for Recipes by Ingredients</h1>
        <hr>
        <br>
        <br>
        <form class="center" action="" method="POST">
            {% csrf_token %}
            {{form}}
            <button type="submit" class="search-button">Search</button>
        </form>
        <br>
        <br>
        {% if recipes_df %}
            {{recipes_df|safe}}
            <br>
            <img class="center" src="data:image/png;base64, {{chart|safe}}">
        {% else %}
            <div style="text-align: center;">No data</div>
        {% endif %}
        <br>
        <br>
        <a href="{% url 'recipes:list' %}">
            <button type="button" class="center back-button">Back</button>
        </a>
    </body>
</html>

src/recipes/templates/recipes/detail.html
<h2>Recipe Details: </h2>
<b>Title: </b> {{object.name}} <br>
<b>Ingredients: </b> {{object.ingredients}} <br>
<b>Cooking Time: </b> {{object.cooking_time}} <br>
<b>Difficulty: </b> {{object.difficulty}} <br>
<img src="{{object.pic.url}}" width="200" height="300" />

src/recipes/templates/recipes/main.html
<h1>Recipes' List</h1>

<table border="1" cellpadding="5" cellspacing="5">
    <tr>
        <td>Recipe Names: </td>
        <td>Recipe Images: </td>
    </tr>
    {% for object in object_list %}
    <tr>
        <td>
            <a href="{{object.get_absolute_url}}">
                {{object.name}}
            </a>
        </td>
        <td>
            <img src="{{object.pic.url}}" width="150" height="200" />
        </td>
    </tr>
    {% endfor %}
</table>

src/recipes/templates/recipes/recipes_home.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <style>
            .center {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }
        </style>
    </head>
    <title>
        Recipe App
    </title>
    <body>
        <img src="{% static 'recipes/images/app-home.jpg' %}" alt="home" width="600" height="400" class="center">
        <h1 style="text-align: center;">Start Cooking!</h1>
    </body>
</html>